<div class="calendar-container">
    <!-- Calendar Header -->
    <div class="calendar-header mb-4">
        <div class="row align-items-center">
            <div class="col-md-6">
                <h4 class="mb-0">
                    <i class="fas fa-calendar-alt"></i>
                    Lịch huấn luyện - <span id="current-month-year"></span>
                </h4>
            </div>
            <div class="col-md-6 text-right">
                <div class="btn-group" role="group">
                    <button type="button" class="btn btn-outline-primary" id="prev-month">
                        <i class="fas fa-chevron-left"></i> Tháng trước
                    </button>
                    <button type="button" class="btn btn-outline-primary" id="next-month">
                        Tháng sau <i class="fas fa-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Calendar Grid -->
    <div class="calendar-grid">
        <div class="calendar-weekdays">
            <div class="weekday">Thứ 2</div>
            <div class="weekday">Thứ 3</div>
            <div class="weekday">Thứ 4</div>
            <div class="weekday">Thứ 5</div>
            <div class="weekday">Thứ 6</div>
            <div class="weekday">Thứ 7</div>
            <div class="weekday">Chủ nhật</div>
        </div>

        <div class="calendar-days" id="calendar-days">
            <!-- Calendar days will be generated by JavaScript -->
        </div>
    </div>

    <!-- Legend -->
    <div class="calendar-legend mt-3">
        <div class="row">
            <div class="col-md-12">
                <div class="legend-item">
                    <span class="legend-color" style="background-color: #28a745;"></span>
                    <span>Có lịch huấn luyện</span>
                </div>
                <div class="legend-item">
                    <span class="legend-color" style="background-color: #ffc107;"></span>
                    <span>Lịch huấn luyện hôm nay</span>
                </div>
                <div class="legend-item">
                    <span class="legend-color" style="background-color: #6c757d;"></span>
                    <span>Ngày khác tháng</span>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Schedule Detail Modal -->
<div class="modal fade" id="scheduleModal" tabindex="-1" role="dialog" aria-labelledby="scheduleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="scheduleModalLabel">
                    <i class="fas fa-calendar-day"></i>
                    Lịch huấn luyện ngày <span id="modal-date"></span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="closeModal()">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="schedule-list">
                    <!-- Schedule items will be loaded here -->
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="closeModal()">Đóng1</button>
                <a href="{{ route('schedule.create') }}" class="btn btn-success">
                    <i class="fas fa-plus"></i> Thêm lịch huấn luyện
                </a>
            </div>
        </div>
    </div>
</div>

<style>
    .calendar-container {
        background: #fff;
        border-radius: 8px;
        padding: 20px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    }

    .calendar-header {
        border-bottom: 2px solid #e9ecef;
        padding-bottom: 15px;
    }

    .calendar-grid {
        margin-top: 20px;
    }

    .calendar-weekdays {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        gap: 1px;
        margin-bottom: 10px;
    }

    .weekday {
        background: #f8f9fa;
        padding: 6px;
        text-align: center;
        font-weight: bold;
        color: #495057;
        border: 1px solid #dee2e6;
        font-size: 12px;
    }

    .calendar-days {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        gap: 1px;
        border: 1px solid #dee2e6;
    }

    .calendar-day {
        min-height: 80px;
        padding: 4px;
        border: 1px solid #dee2e6;
        background: #fff;
        cursor: pointer;
        transition: all 0.3s ease;
        position: relative;
    }

    .calendar-day:hover {
        background: #f8f9fa;
        transform: scale(1.02);
    }

    .calendar-day.other-month {
        background: #f8f9fa;
        color: #6c757d;
    }

    .calendar-day.today {
        background: #fff3cd;
        border: 2px solid #ffc107;
    }

    .calendar-day.has-schedule {
        background: #d4edda;
        border-left: 4px solid #28a745;
    }

    .calendar-day.today.has-schedule {
        background: #fff3cd;
        border: 2px solid #ffc107;
        border-left: 4px solid #28a745;
    }

    .day-number {
        font-weight: bold;
        font-size: 12px;
        margin-bottom: 2px;
    }

    .schedule-count {
        position: absolute;
        top: 2px;
        right: 2px;
        background: #28a745;
        color: white;
        border-radius: 50%;
        width: 16px;
        height: 16px;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 8px;
        font-weight: bold;
    }

    .schedule-preview {
        font-size: 8px;
        color: #495057;
        margin-top: 2px;
        max-height: 30px;
        overflow: hidden;
        line-height: 1.2;
    }

    .schedule-item {
        background: #fff;
        border: 1px solid #dee2e6;
        border-radius: 4px;
        padding: 10px;
        margin-bottom: 10px;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    }

    .schedule-item:last-child {
        margin-bottom: 0;
    }

    .schedule-time {
        font-weight: bold;
        color: #007bff;
        font-size: 12px;
    }

    .schedule-class {
        font-weight: bold;
        color: #495057;
        margin: 5px 0;
    }

    .schedule-subject {
        color: #6c757d;
        font-size: 14px;
        margin-bottom: 5px;
    }

    .schedule-teacher {
        color: #28a745;
        font-size: 14px;
        font-style: italic;
    }

    .schedule-room {
        color: #6c757d;
        font-size: 14px;
    }

    .schedule-shift {
        color: #17a2b8;
        font-size: 14px;
        font-weight: bold;
    }

    .calendar-legend {
        border-top: 1px solid #dee2e6;
        padding-top: 15px;
    }

    .legend-item {
        display: inline-block;
        margin-right: 20px;
        font-size: 12px;
    }

    .legend-color {
        display: inline-block;
        width: 12px;
        height: 12px;
        border-radius: 2px;
        margin-right: 5px;
        vertical-align: middle;
    }

    @media (max-width: 768px) {
        .calendar-day {
            min-height: 60px;
            padding: 2px;
        }

        .day-number {
            font-size: 10px;
        }

        .schedule-preview {
            font-size: 7px;
            max-height: 20px;
        }

        .weekday {
            padding: 4px;
            font-size: 10px;
        }
    }
</style>

<script>
    function closeModal() {
        const modal = $('#scheduleModal');
        modal.modal('hide'); 
    }
    document.addEventListener('DOMContentLoaded', function() {
        let currentDate = new Date();
        let currentMonth = currentDate.getMonth();
        let currentYear = currentDate.getFullYear();

        // Schedule data from server
        const scheduleData = @json($data ?? []);

        // Initialize calendar
        function initCalendar() {
            updateMonthYear();
            generateCalendar();
        }

        // Update month/year display
        function updateMonthYear() {
            const monthNames = [
                'Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6',
                'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12'
            ];
            document.getElementById('current-month-year').textContent =
                monthNames[currentMonth] + ' ' + currentYear;
        }

        // Generate calendar grid
        function generateCalendar() {
            const calendarDays = document.getElementById('calendar-days');
            if (!calendarDays) {
                return;
            }
            calendarDays.innerHTML = '';

            const firstDay = new Date(currentYear, currentMonth, 1);
            const lastDay = new Date(currentYear, currentMonth + 1, 0);
            const startDate = new Date(firstDay);
            startDate.setDate(startDate.getDate() - firstDay.getDay() + 1); // Start from Monday

            const today = new Date();
            const isToday = (date) => {
                return date.toDateString() === today.toDateString();
            };

            const isCurrentMonth = (date) => {
                return date.getMonth() === currentMonth && date.getFullYear() === currentYear;
            };

            // Generate 42 days (6 weeks)
            for (let i = 0; i < 42; i++) {
                const date = new Date(startDate);
                date.setDate(startDate.getDate() + i);

                const dayElement = document.createElement('div');
                dayElement.className = 'calendar-day';

                // Add classes based on date properties
                if (!isCurrentMonth(date)) {
                    dayElement.classList.add('other-month');
                }
                if (isToday(date)) {
                    dayElement.classList.add('today');
                }

                // Check for schedules on this date
                const dateStr = date.toISOString().split('T')[0];
                const daySchedules = scheduleData.filter(schedule => {
                    if (!schedule.schedule_date) return false;
                    const scheduleDate = new Date(schedule.schedule_date);
                    return scheduleDate.toISOString().split('T')[0] === dateStr;
                });

                if (daySchedules.length > 0) {
                    dayElement.classList.add('has-schedule');
                }

                // Day number
                const dayNumber = document.createElement('div');
                dayNumber.className = 'day-number';
                dayNumber.textContent = date.getDate();
                dayElement.appendChild(dayNumber);

                // Schedule count badge
                if (daySchedules.length > 0) {
                    const countBadge = document.createElement('div');
                    countBadge.className = 'schedule-count';
                    countBadge.textContent = daySchedules.length;
                    dayElement.appendChild(countBadge);
                }

                // Schedule preview
                if (daySchedules.length > 0) {
                    const preview = document.createElement('div');
                    preview.className = 'schedule-preview';
                    const firstSchedule = daySchedules[0];
                    const shiftName = firstSchedule.school_shift ? firstSchedule.school_shift.name : 'Ca học';
                    const className = firstSchedule.class ? firstSchedule.class.name : 'Lớp';
                    preview.textContent = `${shiftName} - ${className}`;
                    dayElement.appendChild(preview);
                }

                // Click event
                dayElement.addEventListener('click', function() {
                    showScheduleModal(date, daySchedules);
                });

                calendarDays.appendChild(dayElement);
            }
        }

        // Show schedule modal
        function showScheduleModal(date, schedules) {
            const modal = document.getElementById('scheduleModal');
            const modalDate = document.getElementById('modal-date');
            const scheduleList = document.getElementById('schedule-list');

            // Format date for display
            const dateStr = date.toLocaleDateString('vi-VN', {
                weekday: 'long',
                year: 'numeric',
                month: 'long',
                day: 'numeric'
            });
            modalDate.textContent = dateStr;

            // Clear previous content
            scheduleList.innerHTML = '';

            if (schedules.length === 0) {
                scheduleList.innerHTML = `
                <div class="text-center text-muted py-4">
                    <i class="fas fa-calendar-times fa-3x mb-3"></i>
                    <p>Không có lịch huấn luyện nào trong ngày này</p>
                </div>
            `;
            } else {
                schedules.forEach(schedule => {
                    const scheduleItem = document.createElement('div');
                    scheduleItem.className = 'schedule-item';
                    const startTime = schedule.school_shift ? schedule.school_shift.start_time : '';
                    const endTime = schedule.school_shift ? schedule.school_shift.end_time : '';
                    const className = schedule.class ? schedule.class.name : 'N/A';
                    const subjectName = schedule.subject ? schedule.subject.name : 'N/A';
                    const teacherName = schedule.teacher ? schedule.teacher.name : 'Chưa xác định';
                    const roomName = schedule.room ? schedule.room.name : 'N/A';
                    const shiftName = schedule.school_shift ? schedule.school_shift.name : 'N/A';

                    scheduleItem.innerHTML = `
                    <div class="schedule-time">
                        <i class="fas fa-clock"></i> 
                        ${startTime} - ${endTime}
                    </div>
                    <div class="schedule-class">
                        <i class="fas fa-users"></i> ${className}
                    </div>
                    <div class="schedule-subject">
                        <i class="fas fa-book"></i> ${subjectName}
                    </div>
                    <div class="schedule-teacher">
                        <i class="fas fa-chalkboard-teacher"></i> ${teacherName}
                    </div>
                    <div class="schedule-room">
                        <i class="fas fa-door-open"></i> Phòng: ${roomName}
                    </div>
                    <div class="schedule-shift">
                        <i class="fas fa-clock"></i> Ca: ${shiftName}
                    </div>
                    <div class="mt-2">
                        <a href="/wp-admin/schedule/edit/${schedule.id}" class="btn btn-sm btn-warning">
                            <i class="fas fa-edit"></i> Sửa
                        </a>
                        <a href="/wp-admin/schedule/delete/${schedule.id}" 
                           class="btn btn-sm btn-danger"
                           onclick="return confirm('Bạn có chắc chắn muốn xóa lịch huấn luyện này?')">
                            <i class="fas fa-trash"></i> Xóa
                        </a>
                    </div>
                `;
                    scheduleList.appendChild(scheduleItem);
                });
            }

            $(modal).modal('show');
        }

        // Navigation buttons
        document.getElementById('prev-month').addEventListener('click', function() {
            currentMonth--;
            if (currentMonth < 0) {
                currentMonth = 11;
                currentYear--;
            }
            initCalendar();
        });

        document.getElementById('next-month').addEventListener('click', function() {
            currentMonth++;
            if (currentMonth > 11) {
                currentMonth = 0;
                currentYear++;
            }
            initCalendar();
        });

        document.getElementById('today-btn').addEventListener('click', function() {
            const today = new Date();
            currentMonth = today.getMonth();
            currentYear = today.getFullYear();
            initCalendar();
        });

        // Initialize calendar
        initCalendar();
    });
    
    
    // Initialize calendar
    initCalendar();
});
</script>
